# Generated by Django 5.2.8 on 2025-12-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
