# Generated by Django 5.2.8 on 2025-12-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='next_step',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(blank=True, choices=[('linkedin', 'Linkedin'), ('naukri', 'Naukri'), ('company', 'Company Website'), ('referral', 'Referral'), ('other', 'Other')], max_length=50),
        ),
    ]
