# Generated by Django 5.2.8 on 2025-12-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_salary_max_job_salary_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='follow_up_done',
            field=models.BooleanField(default=False),
        ),
    ]
