# Generated by Django 5.2.8 on 2026-01-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_adminactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivity',
            name='action',
            field=models.CharField(choices=[('login', 'User Logged In'), ('job_created', 'Job Created'), ('job_updated', 'Job Updated'), ('followup_done', 'Follow-up Done'), ('user_locked', 'User Locked'), ('user_unlocked', 'User Unlocked')], max_length=50),
        ),
    ]
